### ISSUE TITLE
Failure linking to anchors on a GitHub page

### ISSUE THREAD

**Issue by philrz** [raviqqe/muffet#144]
I see there's fixed/closed issues that seem similar to this, so I'm not sure why it's failing. I can manually browse to these links successfully.

```
$ ./muffet --version
2.3.2

$ ./muffet --verbose --exclude=linkedin.com --exclude twitter.com --timeout 300 https://www.brimsecurity.com/blog/2020/12/december-2020-updates
...
	id #cut not found	https://github.com/brimsec/zq/blob/master/zql/docs/processors/README.md#cut
	id #example-4 not found	https://github.com/brimsec/zq/tree/master/zql/docs/grouping#example-4
	id #fuse not found	https://github.com/brimsec/zq/blob/master/zql/docs/processors/README.md#fuse
...
```

**Comment by pauloribeiro-codacy** [comment]
I have also been getting lots of these false positives (for example, https://github.com/codacy/docs/issues/367).

**Comment by raviqqe** [comment]
Hi. Sorry for the late reply! Both of your cases are due to actually missing IDs. You can check that by running `curl` on the pages manually.

Note that Muffet does not evaluate any JavaScript scripts and cannot check dynamically generated contents. It's only for static websites as the readme says.

The previous issue: https://github.com/raviqqe/muffet/issues/52

**Comment by pauloribeiro-codacy** [comment]
Thanks for the reply @raviqqe. You're right, unfortunately it seems that the headers in GitHub content generated from Markdown don't have proper `id` attributes.
