### ISSUE TITLE
Support websites in a local directory

### ISSUE THREAD

**Issue by sualeh** [raviqqe/muffet#185]
Support checking links from a website generated in a local directory. Common static website generation tools generate websites in a local directory, which is then uploaded to a web server. It is best to look for broken links before a website is uploaded and published. muffet will be much more useful to website developers if can check a static website generated in a local directory.

**Comment by raviqqe** [comment]
Hi! We've already discussed this topic in #50 and decided not to support the use case because it's not useful for users as we can't test behaviours of all the HTTP static file servers which exist in the world apparently.

Feel free to reopen this issue if you think it's still useful. There is also a good alternative with more ambitious goals like https://github.com/lycheeverse/lychee.
