### ISSUE TITLE
Handle redirects

### ISSUE THREAD

**Issue by dadgar** [raviqqe/muffet#19]
An HTTP redirect isn't necessarily a failing HTTP status code.

```
ERROR   XXX (invalid status code 307)
```

**Comment by raviqqe** [comment]
The documentation ([fasthttp.Client.Get](https://godoc.org/github.com/valyala/fasthttp#Client.Get)) of the `fasthttp` project which `muffet` depends on says the `Get` method follows redirects automatically and `muffet` just calls the function as it is. Could you give some example URLs?

**Comment by dadgar** [comment]
Sure, run it on https://nomadproject.io. You’ll notice the redirect issue and another where it muffet is trying to match the #id only on an html id when it could also be a link.

**Comment by raviqqe** [comment]
Here is a dump of HTTP request headers to `https://nomadproject.io` by `curl`.

```
> curl -LD foo.log https://nomadproject.io/ > /dev/null && cat foo.log
HTTP/1.1 301 https://www.nomadproject.io/
Retry-After: 0
Content-Length: 0
location: https://www.nomadproject.io/
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Accept-Ranges: bytes
Date: Wed, 25 Apr 2018 02:38:48 GMT
Connection: close

HTTP/1.1 200 OK
Cache-Control: max-age=14400
Last-Modified: Tue, 17 Apr 2018 21:08:15 GMT
ETag: "9d6e33067689b922029b043dfaa7e5d8"
Content-Type: text/html
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Content-Length: 135715
Accept-Ranges: bytes
Date: Wed, 25 Apr 2018 02:38:48 GMT
Age: 624617
Connection: keep-alive
Vary: Accept-Encoding
```

As the dump says, the header of `location` is not title-cased, which is why `muffet` cannot handle the redirects.

The project, `fasthttp` which `muffet` uses to throw HTTP requests is one focusing on speed as well as `muffet` and its header parser doesn't allow headers which is not title-cased for the sake of overhead reduction even though the HTTP specification says headers are case insensitive. And when its HTTP request functions fails to parse `Location` headers for redirections, it just returns status codes without handling them.

So, there are 3 options.

- Handle redirection failures manually in `muffet`
- Use `net/http` instead of `fasthttp`
- Let it go as the problem is a kind of niche case

What do you guys think?.

**Comment by raviqqe** [comment]
[fasthttp.Get doesn't follow some redirects.](https://github.com/valyala/fasthttp/blob/5116aa64e038d917b3916a74da456c00643ff1e6/client.go#L770)

**Comment by raviqqe** [comment]
While the original intention about `fasthttp.Get` behavior is vague, the problem is coincidentally resolved by a recent commit as there was other needs (#20) for `muffet` to handle redirects manually.

Although `muffet` seems to work well with the URL (https://nomadproject.io) now, please report problems if you encounter any still.
