### ISSUE TITLE
invalid status code 999

### ISSUE THREAD

**Issue by chrisbenson** [raviqqe/muffet#31]
When I use Muffet on my LinkedIn profile, which certainly works, I get "invalid status code 999".

muffet https://www.linkedin.com/in/chrisbenson

Thanks,
Chris

**Comment by raviqqe** [comment]
According to [this StackOverflow question](https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin), it seems to be due to lack of proper HTTP headers. So, for `muffet` to deal with such websites, it needs something like `--header` option of `curl` command.

Leaving that aside, what is your original intention of running `muffet` against your LinkedIn page? As `muffet` scrapes all pages in a domain, it may result in scanning everything in the LinkedIn website (https://www.linkedin.com). Or do you just want to test your single profile page there?

**Comment by edbrannin** [comment]
I haven't tried running muffet on LinkedIn directly, but I get lots of false failures when I run muffet on a site with social media links (including LinkedIn) in the footer.

(I'd share a link, but its URL is going to change later this week.)

**Comment by raviqqe** [comment]
@edbrannin It's known that Twitter links fail on checks because of missing proper request headers. With which social media's links do you have problems?

**Comment by edbrannin** [comment]
Sorry for the lack of clarity; I meant LinkedIn.

**Comment by raviqqe** [comment]
I recently added `--header` option to `muffet`. Can you try it with LinkedIn links setting proper headers according to [this StackOverflow question](https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin).

**Comment by raviqqe** [comment]
Could it be like a more general feature which allows `muffet` to exclude some URLs by regular expressions?

**Comment by raviqqe** [comment]
Closed by 6d11605. However, because I'm not sure whether the original problem is solved by it, feel free to reopen this issue.

**Comment by edbrannin** [comment]
Thanks!  Between `--header` & `--exclude`, I expect both use-cases in this issue should have workarounds.

**Comment by mattorb** [comment]
Hit this myself, here's some related notes on the headers:

https://stackoverflow.com/a/39021392/191200
