### ISSUE TITLE
--follow-sitemap doesn't follow the sitemap

### ISSUE THREAD

**Issue by zachad** [raviqqe/muffet#316]
Originally added after #32, the `--follow-sitemap` option should read the `sitemap.xml` from a site to determine which pages to check. 

This doesn't appear to work as expected.

Consider a very simple site with three main pages: `/index.html`, `/page1.html` and `/secret.html`.  All three are listed in the `/sitemap.xml`,  and `index.html` links to `page1.html` - however none of the pages link directly to `secret.html`.

When muffet is invoked with `--follow-sitemap` I expect it to read the sitemap and visit each page that is listed there, including `secret.html`. What it seems to do instead, is to start with `/index.html` and scan linked pages recursively _only if_ they're also in the sitemap.  

Is this the intended behavior of this option? Is there a way to achieve our use case?

**Comment by raviqqe** [comment]
I don't remember but I think I, at that time, thought that behavior of adding all pages in the sitemap first is not useful because they are reachable from somewhere else anyway (and in your case, they are not...)

Currently, Muffet treats sitemaps just like `robots.txt` files. `sitemap.xml` files are considered to be allowlists of pages that should be checked while `robots.txt` files are blocklists.

Is the `secret.html` path like another entry point to your page like the auth page that is available only by specific actions?

**Comment by raviqqe** [comment]
I think the `--include-sitemap-xml` flag makes sense. The original feature design of `--follow-sitemap-xml` is rather messed up.

**Comment by raviqqe** [comment]
Can you test #317 on the main branch?

**Comment by nwidger** [comment]
@raviqqe Of course!  We'll give it a try and report back.

And the `sitemap.xml` for our support site currently contains roughly 1,500 pages in total.

**Comment by nwidger** [comment]
@raviqqe The changes you committed to `main` work great, thank you so much for such a quick fix!  Would it be possible to cut a new release of `muffet` containing these changes?

**Comment by zachad** [comment]
Thanks so much @raviqqe for building this new capability, and @nwidger for integrating it so quickly!
