### ISSUE TITLE
Url cache issue

### ISSUE THREAD

**Issue by vmakhaev** [raviqqe/muffet#34]
Muffet goes to same url a lot of times. Shouldn't it go just once?

In this case it makes Linkedin send us 999 status code:
```
muffet -c 10 http://www.ximenavengoechea.com/
http://www.ximenavengoechea.com/
	999	http://www.linkedin.com/in/ximenavengoechea
http://www.ximenavengoechea.com/illustrations/
	999	http://www.linkedin.com/in/ximenavengoechea
http://www.ximenavengoechea.com/contact/
	999	http://www.linkedin.com/in/ximenavengoechea
http://www.ximenavengoechea.com/products/
	999	http://www.linkedin.com/in/ximenavengoechea
http://www.ximenavengoechea.com/design/
	999	http://www.linkedin.com/in/ximenavengoechea
http://www.ximenavengoechea.com/faqs/
	999	http://www.linkedin.com/in/ximenavengoechea
```

**Comment by raviqqe** [comment]
The result of HTTP requests are actually cached although `muffet` shows them just like requests are sent multiple times. The number of HTTP requests sent to a URL is not always one because its caching strategy is best-effort as it is realized by lockless data structure.

For more information, see also #2 and #27.

**Comment by vmakhaev** [comment]
Got it, thanks
