### ISSUE TITLE
Problems with anchors

### ISSUE THREAD

**Issue by geeknoid** [raviqqe/muffet#52]
Using:

```
muffet -c 32 --timeout 10 --exclude http://localhost --exclude https://groups.google.com/forum --exclude https://github.com/istio/istio.io/issues/new.* https://istio.io 
```

Produces a bunch of incorrect error messages of the form:

```
https://istio.io/docs/reference/config/policy-and-telemetry/adapters/memquota/
	id #duration not found	https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration
https://istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/
	id #struct not found	https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct
https://istio.io/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/
	id #duration not found	https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration
```
These ID values are all present in the target HTML page, so these errors shouldn't be produced.

**Comment by raviqqe** [comment]
Sorry to say this but this issue is not going to be fixed in the near future and probably out of scope of this project because Muffet is not able to run JavaScript and integrating some JS engine into Muffet leads to quite a bit of code complexity increase and performance decrease. If you need link checking for those JS-rendered  anchors, please use some of browser automation libraries like [Selenium](https://www.seleniumhq.org/). But thanks for reporting the issue!

**Comment by fg-j** [comment]
I'm seeing this problem too. I definitely understand why it's out of scope to run javascript. A cool heuristic could be a flag like `--strip-anchors` or something that strips the anchor off the end of URLs before checking them. That would allow link checks to pass even on pages that are running javascript (without having to `--exclude "#"`).

**Comment by raviqqe** [comment]
We already have the option called `--ignore-fragments`.

**Comment by fg-j** [comment]
Bet. I misunderstood the meaning of "fragment". Thanks for the clarification.
